import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          src="/alone-gno-mo.png"
          alt="App Logo"
          width={256}
          height={256}
        />
        <h1>Welcome to the Brastlewark social network!</h1>
      </main>
    </div>
  );
}
